name: Metrics & Snake

on:
  schedule:
    - cron: "0 * * * *" # Every hour
  workflow_dispatch:
  push:
    branches: ["main", "master"]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Generate GitHub Metrics
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          user: TechieGeekee
          template: classic
          output: dist/metrics.svg
          base: header, activity, community, repositories, metadata
          config_timezone: Asia/Calcutta
          plugin_activity: yes
          plugin_code: yes
          plugin_followup: yes
          plugin_fortune: yes
          plugin_gists: yes
          plugin_habits: yes
          plugin_introduction: yes
          plugin_isocalendar: yes
          plugin_leetcode: yes
          plugin_lines: yes
          plugin_notable: yes
          plugin_pagespeed: yes
          plugin_posts: yes
          plugin_projects: yes
          plugin_repositories: yes
          plugin_splatoon: yes
          plugin_steam: yes
          plugin_stock: yes
          plugin_traffic: yes
          plugin_wakatime: yes

      - name: Generate Snake Animation (SVG + GIF)
        uses: Platane/snk@v3
        with:
          github_user_name: ${{ github.repository_owner }}
          outputs: |
            dist/github-snake.svg
            dist/github-snake-dark.svg?palette=github-dark
            dist/ocean.gif?color_snake=orange&color_dots=#bfd6f6,#8dbdff,#64a1f4,#4b91f1,#3c7dd9

      - name: Push generated files to the repo
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "chore: update metrics and snake animations"
          branch: ${{ github.ref_name }}
          file_pattern: dist/*
